package main

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestEmbeddedFrontendMatchesCanonical guards against frontend drift.
//
// public/ at the repository root is the single source of truth for the web
// frontend. cmd/huzbackend/public/ is the copy that is actually embedded into
// the binary via go:embed (see main.go); it is generated by "make sync-public"
// and must never be edited by hand.
//
// This test fails whenever the two copies diverge, so a plain "go test ./..."
// (or "go test" in CI) always catches an out-of-sync frontend.
func TestEmbeddedFrontendMatchesCanonical(t *testing.T) {
	canonicalRoot := filepath.Join("..", "..", "public")

	sub, err := fs.Sub(publicFS, "public")
	if err != nil {
		t.Fatalf("fs.Sub(public): %v", err)
	}

	// Skip names go:embed itself would skip: entries starting with '.' or '_'.
	skip := func(name string) bool {
		base := filepath.Base(name)
		return strings.HasPrefix(base, ".") || strings.HasPrefix(base, "_")
	}

	// 1) Every embedded file must exist on disk with identical content.
	embeddedCount := 0
	err = fs.WalkDir(sub, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || skip(path) {
			return nil
		}
		embeddedCount++
		want, readErr := fs.ReadFile(sub, path)
		if readErr != nil {
			return readErr
		}
		got, readErr := os.ReadFile(filepath.Join(canonicalRoot, filepath.FromSlash(path)))
		if readErr != nil {
			t.Errorf("embedded file is missing from public/: %s (run 'make sync-public')", path)
			return nil
		}
		if string(got) != string(want) {
			t.Errorf("content mismatch between embedded copy and public/: %s (run 'make sync-public')", path)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk embedded fs: %v", err)
	}
	if embeddedCount == 0 {
		t.Fatal("embedded frontend is empty; did go:embed resolve public/?")
	}

	// 2) Every canonical file must exist in the embedded copy.
	canonicalCount := 0
	err = filepath.WalkDir(canonicalRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(canonicalRoot, path)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)
		if skip(rel) {
			return nil
		}
		canonicalCount++
		if _, statErr := fs.Stat(sub, rel); statErr != nil {
			t.Errorf("public/%s is missing from the embedded copy (run 'make sync-public')", rel)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk canonical fs: %v", err)
	}
	if canonicalCount == 0 {
		t.Fatal("canonical public/ directory appears empty")
	}
}
