# These are supported funding model platforms

github: [sagehuz]
patreon: nguyentrungkhiem
open_collective: khiemtrung
ko_fi: khiemtrung
issuehunt: sagehuz
buy_me_a_coffee: khiemtrung
thanks_dev: sagehuz
